services:
  mysql-cart:
    image: mysql:8.0.0
    container_name: mysql-cart
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart_db
      MYSQL_USER: cart_user
      MYSQL_PASSWORD: cart_pass
    ports:
      # expor localmente na porta 3307 - "3307:3307"
      - "3309:3306"
    volumes:
      - mysql-cart-data:/var/lib/mysql
    networks:
      - cart-network
    command: --disable-ssl --skip-ssl

  cart-service:
    build: .
    profiles:
      - application
    container_name: cart-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cart:3306/cart_db
      SPRING_DATASOURCE_USERNAME: cart_user
      SPRING_DATASOURCE_PASSWORD: cart_pass
    depends_on:
      - mysql-cart
      #- rabbitmq
    ports:
      - "8084:8084"
    command: >
      sh -c "
        echo 'Aguardando MySQL...';
        until mysqladmin ping -h mysql-cart --silent; do
          echo 'Ainda não disponivel...';
          sleep 2;
        done;
        echo 'MySQL pronto! A iniciar aplicacao...';
        java -jar app.jar
      "
    networks:
      - cart-network

volumes:
  mysql-cart-data:

networks:
  cart-network:
